export const data = [
  {
    song_name: "Echoes of Tomorrow",
    artist: "Luna Waves",
    date_streamed: "2025-01-25",
    stream_count: 3,
    user_id: "U10234",
  },
  {
    song_name: "Chasing Horizons",
    artist: "Nova Sky",
    date_streamed: "2025-01-28",
    stream_count: 1,
    user_id: "U10567",
  },
  {
    song_name: "Midnight Reverie",
    artist: "Aurora Night",
    date_streamed: "2025-01-26",
    stream_count: 5,
    user_id: "U10982",
  },
  {
    song_name: "Waves of Serenity",
    artist: "Ocean Drift",
    date_streamed: "2025-01-29",
    stream_count: 2,
    user_id: "U10234",
  },
  {
    song_name: "Golden Skies",
    artist: "Sunset Echoes",
    date_streamed: "2025-01-30",
    stream_count: 4,
    user_id: "U11021",
  },
  {
    song_name: "Velvet Dreams",
    artist: "Starfire",
    date_streamed: "2025-01-28",
    stream_count: 3,
    user_id: "U10355",
  },
  {
    song_name: "Cosmic Trails",
    artist: "Lunar Glow",
    date_streamed: "2025-01-27",
    stream_count: 7,
    user_id: "U10412",
  },
  {
    song_name: "Sunset Lullaby",
    artist: "Horizon Bloom",
    date_streamed: "2025-01-30",
    stream_count: 2,
    user_id: "U10198",
  },
  {
    song_name: "Starlit Voyage",
    artist: "Galaxy Pulse",
    date_streamed: "2025-01-29",
    stream_count: 5,
    user_id: "U10845",
  },
  {
    song_name: "Moonlit Whispers",
    artist: "Celestial Muse",
    date_streamed: "2025-01-28",
    stream_count: 6,
    user_id: "U10567",
  },
  {
    song_name: "Aurora Lights",
    artist: "Sky Dreamers",
    date_streamed: "2025-01-29",
    stream_count: 3,
    user_id: "U10789",
  },
  {
    song_name: "Ethereal Skies",
    artist: "Dreamwave",
    date_streamed: "2025-01-27",
    stream_count: 4,
    user_id: "U10611",
  },
  {
    song_name: "Northern Echo",
    artist: "Arctic Bloom",
    date_streamed: "2025-01-25",
    stream_count: 8,
    user_id: "U10567",
  },
  {
    song_name: "Solar Flare",
    artist: "Galactic Beats",
    date_streamed: "2025-01-26",
    stream_count: 2,
    user_id: "U10890",
  },
  {
    song_name: "Serenade of Stars",
    artist: "Harmonic Pulse",
    date_streamed: "2025-01-30",
    stream_count: 5,
    user_id: "U10912",
  },
  {
    song_name: "Dreamcatcher",
    artist: "Night Bloom",
    date_streamed: "2025-01-28",
    stream_count: 6,
    user_id: "U10645",
  },
  {
    song_name: "Mystic Horizon",
    artist: "Aurora Drift",
    date_streamed: "2025-01-27",
    stream_count: 7,
    user_id: "U10199",
  },
  {
    song_name: "Twilight Reverie",
    artist: "Sunrise Symphony",
    date_streamed: "2025-01-29",
    stream_count: 4,
    user_id: "U11000",
  },
  {
    song_name: "Celestial Journey",
    artist: "Eclipse Waves",
    date_streamed: "2025-01-30",
    stream_count: 3,
    user_id: "U10278",
  },
  {
    song_name: "Galactic Drift",
    artist: "Nova Pulse",
    date_streamed: "2025-01-28",
    stream_count: 1,
    user_id: "U10301",
  },
  {
    song_name: "Stellar Night",
    artist: "Moon Glow",
    date_streamed: "2025-01-26",
    stream_count: 5,
    user_id: "U10982",
  },
  {
    song_name: "Radiant Harmony",
    artist: "Star Symphony",
    date_streamed: "2025-01-25",
    stream_count: 3,
    user_id: "U10734",
  },
  {
    song_name: "Whispers of Time",
    artist: "Luna Serenade",
    date_streamed: "2025-01-27",
    stream_count: 8,
    user_id: "U11045",
  },
  {
    song_name: "Dawn's Melody",
    artist: "Aurora Pulse",
    date_streamed: "2025-01-30",
    stream_count: 2,
    user_id: "U10234",
  },
  {
    song_name: "Stellar Echoes",
    artist: "Galaxy Rhythm",
    date_streamed: "2025-01-26",
    stream_count: 7,
    user_id: "U10511",
  },
  {
    song_name: "Lunar Dreamscape",
    artist: "Horizon Glow",
    date_streamed: "2025-01-28",
    stream_count: 5,
    user_id: "U10392",
  },
  {
    song_name: "Nebula Serenade",
    artist: "Starry Pulse",
    date_streamed: "2025-01-29",
    stream_count: 6,
    user_id: "U10411",
  },
  {
    song_name: "Astral Vision",
    artist: "Moonlight Muse",
    date_streamed: "2025-01-27",
    stream_count: 9,
    user_id: "U10971",
  },
  {
    song_name: "Eclipse Symphony",
    artist: "Galaxy Drift",
    date_streamed: "2025-01-30",
    stream_count: 4,
    user_id: "U11012",
  },
  {
    song_name: "Harmony of Stars",
    artist: "Lunar Pulse",
    date_streamed: "2025-01-29",
    stream_count: 5,
    user_id: "U10722",
  },
  {
    song_name: "Cosmic Waves",
    artist: "Celestial Bloom",
    date_streamed: "2025-01-27",
    stream_count: 8,
    user_id: "U10643",
  },
  {
    song_name: "Celestial Drift",
    artist: "Starlight Pulse",
    date_streamed: "2025-01-26",
    stream_count: 3,
    user_id: "U10312",
  },
  {
    song_name: "Starfall Lullaby",
    artist: "Aurora Bloom",
    date_streamed: "2025-01-25",
    stream_count: 9,
    user_id: "U10121",
  },
  {
    song_name: "Echoes of Light",
    artist: "Luna Glow",
    date_streamed: "2025-01-29",
    stream_count: 4,
    user_id: "U10409",
  },
  {
    song_name: "Radiant Drift",
    artist: "Eclipse Waves",
    date_streamed: "2025-01-30",
    stream_count: 2,
    user_id: "U10734",
  },
  {
    song_name: "Horizon Reverie",
    artist: "Stellar Bloom",
    date_streamed: "2025-01-26",
    stream_count: 5,
    user_id: "U10289",
  },
  {
    song_name: "Twilight Pulse",
    artist: "Celestial Muse",
    date_streamed: "2025-01-28",
    stream_count: 7,
    user_id: "U11009",
  },
  {
    song_name: "Serenade of Dreams",
    artist: "Aurora Echoes",
    date_streamed: "2025-01-29",
    stream_count: 6,
    user_id: "U10871",
  },
  {
    song_name: "Galactic Symphony",
    artist: "Stellar Drift",
    date_streamed: "2025-01-27",
    stream_count: 1,
    user_id: "U11045",
  },
  {
    song_name: "Waves of Eternity",
    artist: "Starry Symphony",
    date_streamed: "2025-01-25",
    stream_count: 9,
    user_id: "U10632",
  },
  {
    song_name: "Lunar Voyage",
    artist: "Galaxy Pulse",
    date_streamed: "2025-01-28",
    stream_count: 3,
    user_id: "U10211",
  },
  {
    song_name: "Nebula Glow",
    artist: "Moonlight Drift",
    date_streamed: "2025-01-30",
    stream_count: 4,
    user_id: "U10377",
  },
  {
    song_name: "Aurora Symphony",
    artist: "Eclipse Pulse",
    date_streamed: "2025-01-26",
    stream_count: 8,
    user_id: "U10899",
  },
  {
    song_name: "Harmonic Voyage",
    artist: "Celestial Drift",
    date_streamed: "2025-01-27",
    stream_count: 5,
    user_id: "U10465",
  },
  {
    song_name: "Serenity of Stars",
    artist: "Luna Bloom",
    date_streamed: "2025-01-28",
    stream_count: 2,
    user_id: "U11012",
  },
  {
    song_name: "Twilight Symphony",
    artist: "Stellar Horizon",
    date_streamed: "2025-01-29",
    stream_count: 1,
    user_id: "U10834",
  },
  {
    song_name: "Eclipse Serenade",
    artist: "Galaxy Glow",
    date_streamed: "2025-01-30",
    stream_count: 7,
    user_id: "U10721",
  },
];
